# Generated by Django 4.2.6 on 2023-10-26 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_about', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.CharField(max_length=100)),
                ('user_city', models.CharField(max_length=100)),
                ('user_country', models.CharField(max_length=100)),
                ('user_ZIPCODE', models.IntegerField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
