# Generated by Django 4.2.6 on 2023-10-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_ZIPCODE',
            field=models.IntegerField(),
        ),
    ]
