# Generated by Django 4.2.6 on 2023-10-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_userprofile_user_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_ZIPCODE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_address',
            field=models.CharField(max_length=200),
        ),
    ]
