# Generated by Django 4.2.6 on 2023-10-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_userprofile_user_zipcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
