# Generated by Django 4.2.6 on 2023-11-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_userprofile_user_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pin', models.IntegerField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('rest_cantact_no', models.IntegerField(max_length=20)),
                ('owner_contact_no', models.IntegerField(max_length=20)),
                ('ownername', models.CharField(max_length=100)),
                ('owneremail', models.EmailField(max_length=100)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('menu_image', models.ImageField(upload_to='menu_images/')),
                ('restaurant_image', models.ImageField(upload_to='resta_images/')),
            ],
        ),
    ]
