# Generated by Django 4.2.6 on 2023-11-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_ZIPCODE',
            field=models.IntegerField(default=0),
        ),
    ]
