# Generated by Django 4.2.6 on 2024-06-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.CharField(default='dfjdj', max_length=1000),
            preserve_default=False,
        ),
    ]
