# Generated by Django 4.2.6 on 2024-06-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_item_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
