# Generated by Django 4.2.3 on 2024-06-17 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_alter_cart_item_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('phone_number', models.ImageField(upload_to='')),
                ('Email', models.TextField()),
                ('Address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pin_code', models.IntegerField()),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.cart')),
            ],
        ),
    ]
