# Generated by Django 4.2.6 on 2024-06-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_order_rename_item_count_cart_quantity_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='item_count',
        ),
    ]
