# Generated by Django 4.2.3 on 2024-06-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
