# Generated by Django 4.2.6 on 2024-06-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_rename_quantity_cart_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delevery_status',
            field=models.BooleanField(default=False),
        ),
    ]
