# Generated by Django 4.2.3 on 2024-06-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_order_details_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
