# Generated by Django 4.2.3 on 2024-06-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_alter_order_details_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.item'),
        ),
    ]
