# Generated by Django 4.2.6 on 2024-06-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_order_delevery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ManyToManyField(to='restaurant.restaurant'),
        ),
    ]
