# Generated by Django 4.2.6 on 2024-06-22 12:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0021_ratingreviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatingReviews',
            new_name='Feedback',
        ),
    ]
